### ISSUE TITLE
[ISSUE] mongo error on start project

### ISSUE THREAD

**Issue by rrfaria** [strapi/strapi-template-blog#5]
Instead I use relational db, I choose mongo 
and then when it was importing data it shows this error
It works! I created all project and backend was working fine even with the fallow error but frontend not:
```
[develop:backend ] model {
[develop:backend ]   title: 'A bug is becoming a meme on the internet',
[develop:backend ]   content: "It's the story of a user named **Omer Barnir** who reported a bug in 2005 on the MySQL [bug report platform](https://bugs.mysql.com/)\n" +
[develop:backend ]     '\n' +
[develop:backend ]     "But the thing is that Omer never get an answer. 15 years later, the bug has never been fix and people are starting to make fun out of it. We let you take a look at the conversation [here](https://bugs.mysql.com/bug.php?id=11472), it's pretty funny",
[develop:backend ]   publishedAt: '2020-07-16T10:00:00.000Z',
[develop:backend ]   status: 'published',
[develop:backend ]   slug: 'a-bug-is-becoming-a-meme-on-the-internet',
[develop:backend ]   category: { id: 2 },
[develop:backend ]   author: { id: 2 },
[develop:backend ]   description: 'How a bug on MySQL is becoming a meme on the internet',
[develop:backend ]   image: null
[develop:backend ] } CastError: Cast to ObjectId failed for value "{ id: 2 }" at path "category"
[develop:backend ]     at model.Query.exec (/home/ai/Documentos/Projetos/meu-blog-strapi/backend/node_modules/mongoose/lib/query.js:4371:21)
[develop:backend ]     at model.Query.Query.then (/home/ai/Documentos/Projetos/meu-blog-strapi/backend/node_modules/mongoose/lib/query.js:4463:15)
[develop:backend ]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[develop:backend ]     at runNextTicks (internal/process/task_queues.js:66:3)
[develop:backend ]     at processImmediate (internal/timers.js:434:9) {
[develop:backend ]   messageFormat: undefined,
[develop:backend ]   stringValue: '"{ id: 2 }"',
[develop:backend ]   kind: 'ObjectId',
[develop:backend ]   value: { id: 2 },
[develop:backend ]   path: 'category',
[develop:backend ]   reason: Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
[develop:backend ]       at new ObjectID (/home/ai/Documentos/Projetos/meu-blog-strapi/backend/node_modules/bson/lib/bson/objectid.js:59:11)
[develop:backend ]       at castObjectId (/home/ai/Documentos/Projetos/meu-blog-strapi/backend/node_modules/mongoose/lib/cast/objectid.js:25:12)
[develop:backend ]       at ObjectId.cast (/home/ai/Documentos/Projetos/meu-blog-strapi/backend/node_modules/mongoose/lib/schema/objectid.js:267:12)
[develop:backend ]       at ObjectId.SchemaType.applySetters (/home/ai/Documentos/Projetos/meu-blog-strapi/backend/node_modules/mongoose/lib/schematype.js:1075:12)
[develop:backend ]       at ObjectId.SchemaType._castForQuery (/home/ai/Documentos/Projetos/meu-blog-strapi/backend/node_modules/mongoose/lib/schematype.js:1510:15)
[develop:backend ]       at ObjectId.SchemaType.castForQuery (/home/ai/Documentos/Projetos/meu-blog-strapi/backend/node_modules/mongoose/lib/schematype.js:1500:15)
[develop:backend ]       at ObjectId.SchemaType.castForQueryWrapper (/home/ai/Documentos/Projetos/meu-blog-strapi/backend/node_modules/mongoose/lib/schematype.js:1477:20)
[develop:backend ]       at castUpdateVal (/home/ai/Documentos/Projetos/meu-blog-strapi/backend/node_modules/mongoose/lib/helpers/query/castUpdate.js:528:19)
[develop:backend ]       at walkUpdatePath (/home/ai/Documentos/Projetos/meu-blog-strapi/backend/node_modules/mongoose/lib/helpers/query/castUpdate.js:266:22)
[develop:backend ]       at castUpdate (/home/ai/Documentos/Projetos/meu-blog-strapi/backend/node_modules/mongoose/lib/helpers/query/castUpdate.js:94:7)
[develop:backend ]       at model.Query._castUpdate (/home/ai/Documentos/Projetos/meu-blog-strapi/backend/node_modules/mongoose/lib/query.js:4556:10)
[develop:backend ]       at castDoc (/home/ai/Documentos/Projetos/meu-blog-strapi/backend/node_modules/mongoose/lib/query.js:4585:18)
[develop:backend ]       at model.Query._updateThunk (/home/ai/Documentos/Projetos/meu-blog-strapi/backend/node_modules/mongoose/lib/query.js:3754:20)
[develop:backend ]       at model.Query.<anonymous> (/home/ai/Documentos/Projetos/meu-blog-strapi/backend/node_modules/mongoose/lib/query.js:3852:23)
[develop:backend ]       at model.Query._wrappedThunk [as _updateOne] (/home/ai/Documentos/Projetos/meu-blog-strapi/backend/node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8)
[develop:backend ]       at /home/ai/Documentos/Projetos/meu-blog-strapi/backend/node_modules/kareem/index.js:278:20
[develop:backend ] }
```

To solve it I just updated imported articles selecting image cartegory and writer
and I found a bug on frontend when the article has no image 
to solve this I just did on my-blog/frontend/components/card.js
```
<Image image={article.image || {}} />
```
the full component:
```


import React from "react";
import Link from "next/link";
import Image from "./image";

const Card = ({ article }) => {
  return (
    <Link as={`/article/${article.slug}`} href="/article/[id]">
      <a className="uk-link-reset">
        <div className="uk-card uk-card-muted">
          <div className="uk-card-media-top">
            <Image image={article.image || {}} />
          </div>
          <div className="uk-card-body">
            <p id="category" className="uk-text-uppercase">
              {(article.category || {}).name}
            </p>
            <p id="title" className="uk-text-large">
              {article.title}
            </p>
          </div>
        </div>
      </a>
    </Link>
  );
};

export default Card;

```
After I solve this I update Alternative text and Caption on each image
on media Library

them all works fine 

I hope it can help someone.. 

and I suggest a fix to instead of try to set Id it gets the id from mongo and update the collections 
because the problem was because it was trying to add a relational id to a non relation db

**Comment by remidej** [comment]
I moved this issue because this is a problem with the underlying template, not the Next blog itself

**Comment by markkaylor** [comment]
In response to: https://github.com/strapi/community-content/issues/87#issuecomment-843081671

@purnimagupta The issue is actually with the seed data.  If you look in https://github.com/strapi/strapi-template-blog/blob/master/template/data/data.json you will see we are referencing relations by id.  For example: 

```
"articles": {
  "title": "some title"
  "category": 1
}
 ```

The problem is mongo doesn't use an integer as an ID, it uses an ObjectId like `ObjectId("60a3a665cf51721e07a1f600")`

To get the app working, what I can suggest you do as a (not so ideal) workaround is:
1. `cd backend`
2. Open `config/functions/bootstrap.js`
3. Comment lines: 151, 153, and 154
```
  // await importCategories();
  await importHomepage();
  // await importWriters();
  // await importArticles();
  await importGlobal();
```
4. (still in backend directory) `yarn develop`
5. Create a writer, create a category, create an article and add your writer and category as relations
6. Then you have two options:
    a.) Leave your backend running, in a new terminal window go to your monorepo, `cd frontend` and `yarn develop`
    b.) Kill the running backend `..` back to your monorepo and `yarn develop` (this will launch the develop command for both backend and frontend)

Hopefully we will resolve the seed issue soon, but unfortunately for the time being using mongo db you will have to enter your data by hand in Strapi.  Let me know if you have any questions.  I tested this and it worked.

**Comment by markkaylor** [comment]
@purnimagupta Forgot to mention you will need to drop your mongo database before doing the above:

```
db.dropDatabase()
```

**Comment by purnimagupta** [comment]
Hi @markkaylor,

I commented out the lines 151, 153, 154 inside `config/functions/bootstrap.js` and restarted the backend server again. 

When I logged into the Strapi Admin Panel again, it was still populated with data from the JSON file. 

Before I saw your `db.dropDatabase()`  command, I had done the followings:

1. I changed `id` to `myId` in the `data.json file` and created the same field on the required collections so that It doesn't clash with the MongoDB automatically generated `id`

2. Also, changed some code inside `config/functions/bootstrap` file on line no. 36 to `role: publicRole.myId,` and line no 56 to `.update({ id: permission.myId }, { enabled: true })` 

3. Uncommented 151, 153, 154 these lines

4. In the backend, pictures that are inside the `data/uploads/...jpg` files aren't getting uploaded to the **articles** collections. All the image fields were empty. So I'm not sure whether it's the script or the mongodb? 

Anyway, when I ran the frontend app, I ran into errors like below as expected due to images being null I guess:

```
Cannot query field &quot;childImageSharp&quot; on type &quot;StrapiArticleAuthorPicture&quot;.

Cannot query field "image" on type "StrapiArticle".

...More
```

To expedite the process, I selected the pictures which were already in the Strapi Media Library collection. Then the website ran as expected. 

![image](https://user-images.githubusercontent.com/4417175/118671499-25076e00-b815-11eb-9281-b232fad0d95a.png)

when you click on some particular blog

![image](https://user-images.githubusercontent.com/4417175/118671623-449e9680-b815-11eb-882f-463766a44322.png)


So my question is to you what could be the reason that image didn't upload to `article` collections? Let me know. Thanks

**Comment by markkaylor** [comment]
The `bootstrap.js` script is only going to run if the database is empty.  So I'm not sure your changes were taken into account.  That's why you still see the data from data.json in the strapi backend.  

I believe the only images you see belong to collection types that do not have relations in the data.json

> Also, changed some code inside config/functions/bootstrap file on line no. 36 to role: publicRole.myId, and line no 56 to .update({ id: permission.myId }, { enabled: true })

I think even if you drop the db this change will throw an error because `myId` does not exist on `publicRole` which is defined on line 27

```
  const publicRole = await strapi
    .query("role", "users-permissions")
    .findOne({ type: "public" });
```

When you add the images in the backend it works because now a mongo id has been added.  In fact that can also be a solution for you.  Just upload new images for all the articles and writers.
